# Generated by Django 4.2.1 on 2023-06-05 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_userprofile_remove_libro_autor_remove_reseña_libro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='apellido',
            new_name='comuna',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='nombre',
            new_name='profesion',
        ),
    ]
