# Generated by Django 4.2.1 on 2023-06-05 01:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0003_rename_apellido_userprofile_comuna_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='PerfilDeUsuario',
        ),
    ]
